name: flutterveil_example
description: Example app for the flutterveil crash monitoring SDK.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutterveil:
    path: ../
